<a href="https://colab.research.google.com/github/mohmaed7777/Deep-learning-with-pytorch/blob/master/1_D_TorchTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Preparation**

Import the following libraries that we wil use for this lab:

In [40]:
import torch 
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline 

In [41]:
print(torch.__version__)

1.6.0+cu101


This is the function for plotting diagrams. You will use this function to plot the vectors in Coordinate system.

In [42]:
# Plot vecotrs, please keep the parameters in the same length
# @param: Vectors = [{"vector": vector variable, "name": name of vector, "color": color of the vector on diagram}]
    
def plotVec(vectors):
    ax = plt.axes()
    
    # For loop to draw the vectors
    for vec in vectors:
        ax.arrow(0, 0, *vec["vector"], head_width = 0.05,color = vec["color"], head_length = 0.1)
        plt.text(*(vec["vector"] + 0.1), vec["name"])
    
    plt.ylim(-2,2)
    plt.xlim(-2,2)

# **Types and shapes:**

In [43]:
# convert an integer of python lists with length 5 to 
# a pytorch tensors as follows : 
a = [1, 2, 3, 4, 5]
ints_to_tensors = torch.tensor(a)
ints_to_tensors


tensor([1, 2, 3, 4, 5])

In [44]:
print('The dtype of tensor object after converting it to torch tensor: ',ints_to_tensors.dtype)
print('The type of tensor object after converting it to torch tensor: ', ints_to_tensors.type())

The dtype of tensor object after converting it to torch tensor:  torch.int64
The type of tensor object after converting it to torch tensor:  torch.LongTensor


In [47]:
type(ints_to_tensors)

torch.Tensor

In [48]:
# convert a float list with length 5 to a tensor :
float_to_tensor = torch.tensor([0.0, 1.0,2.0, 3.0, 4.0])
float_to_tensor

tensor([0., 1., 2., 3., 4.])

In [49]:
print('The dtype of tensor object after converting it to tensors==> ',float_to_tensor.dtype)
print('The type of tensor after converting it to a tensor==> ',float_to_tensor.type())

The dtype of tensor object after converting it to tensors==>  torch.float32
The type of tensor after converting it to a tensor==>  torch.FloatTensor


In [50]:
# Convert a float python list to a float tensor : 
list_of_floats = [0.0, 1.0, 2.0, 3.0, 4.0]
float_int_tensors = torch.tensor(list_of_floats, dtype=torch.int64)
float_int_tensors

tensor([0, 1, 2, 3, 4])

In [51]:
float_int_tensors.type()

'torch.LongTensor'

In [52]:
float_int_tensors.dtype

torch.int64

From the previous examples, you see that torch.tensor() converts the list to the tensor type, which is similar to the original list type. However, what if you want to convert the list to a certain tensor type? torch contains the methods required to do this conversion. The following code converts an integer list to float tensor:

In [53]:
# Convert an integer list with length 5 to a float tensors:
new_float_tensor = torch.FloatTensor([1, 2, 3, 4, 5])
print('The type of the new tensor==> ',new_float_tensor.type())
print('The dtype of the new tensor==> ',new_float_tensor.dtype)

The type of the new tensor==>  torch.FloatTensor
The dtype of the new tensor==>  torch.float32


In [54]:
new_float_tensor = torch.FloatTensor([0, 1, 2, 3, 4])

In [55]:
# Another method to convert the integer list to float tensor:
old_int_tensor = torch.tensor([1, 2, 3, 4])
new_float_tensor = old_int_tensor.type(torch.FloatTensor)
print('The type of the new float tensor', new_float_tensor.type())
new_float_tensor

The type of the new float tensor torch.FloatTensor


tensor([1., 2., 3., 4.])

The tensor_obj.size() helps you to find out the size of the tensor_obj. The tensor_obj.ndimension() shows the dimension of the tensor object.

In [56]:
print('The size of the new_float_tensor==> ', new_float_tensor.size())
print('The number of dimensions of the new_float_tensors==>',new_float_tensor.ndimension(),'-Dimensional Tensor(Vector)')


The size of the new_float_tensor==>  torch.Size([4])
The number of dimensions of the new_float_tensors==> 1 -Dimensional Tensor(Vector)


The tensor_obj.view(row, column) is used for reshaping a tensor object.

What if you have a tensor object with torch.Size([5]) as a new_float_tensor as shown in the previous example?
After you execute new_float_tensor.view(5, 1), the size of new_float_tensor will be torch.Size([5, 1]).
This means that the tensor object new_float_tensor has been reshaped from a one-dimensional tensor object with 5 elements to a two-dimensional tensor object with 5 rows and 1 column.

In [58]:
# Introduce the tensor_obj.view(rows, columns) method:
twoD_float_tensor = new_float_tensor.view(4,1)
print('Original size: ', new_float_tensor)
print('Size after view method ', twoD_float_tensor)

Original size:  tensor([1., 2., 3., 4.])
Size after view method  tensor([[1.],
        [2.],
        [3.],
        [4.]])


In [59]:
twoD_float_tensor

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [60]:
twoD_float_tensor.ndimension()

2

In [61]:
# Introduce the use of -1 in tensor_obj.view(rows, columns)method
twoD_float_tensor = new_float_tensor.view(-1, 1)
print('Original size: ', new_float_tensor)
print('Size after view method ', twoD_float_tensor)

Original size:  tensor([1., 2., 3., 4.])
Size after view method  tensor([[1.],
        [2.],
        [3.],
        [4.]])


In [62]:
x = torch.tensor([2, 4, 5, 66])
p = x.view(-1, 1)
p

tensor([[ 2],
        [ 4],
        [ 5],
        [66]])

In [63]:
p.type()

'torch.LongTensor'

**Convert Numpy array to Tensors:**