<a href="https://colab.research.google.com/github/mohmaed7777/Deep-learning-with-pytorch/blob/master/1_D_TorchTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Preparation**

Import the following libraries that we wil use for this lab:

In [2]:
import torch 
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline 

In [3]:
print(torch.__version__)

1.6.0+cu101


This is the function for plotting diagrams. You will use this function to plot the vectors in Coordinate system.

In [4]:
# Plot vecotrs, please keep the parameters in the same length
# @param: Vectors = [{"vector": vector variable, "name": name of vector, "color": color of the vector on diagram}]
    
def plotVec(vectors):
    ax = plt.axes()
    
    # For loop to draw the vectors
    for vec in vectors:
        ax.arrow(0, 0, *vec["vector"], head_width = 0.05,color = vec["color"], head_length = 0.1)
        plt.text(*(vec["vector"] + 0.1), vec["name"])
    
    plt.ylim(-2,2)
    plt.xlim(-2,2)

# **Types and shapes:**

In [5]:
# convert an integer of python lists with length 5 to 
# a pytorch tensors as follows : 
a = [1, 2, 3, 4, 5]
ints_to_tensors = torch.tensor(a)
ints_to_tensors


tensor([1, 2, 3, 4, 5])

In [6]:
print('The dtype of tensor object after converting it to torch tensor: ',ints_to_tensors.dtype)
print('The type of tensor object after converting it to torch tensor: ', ints_to_tensors.type())

The dtype of tensor object after converting it to torch tensor:  torch.int64
The type of tensor object after converting it to torch tensor:  torch.LongTensor


In [7]:
type(ints_to_tensors)

torch.Tensor

In [8]:
# convert a float list with length 5 to a tensor :
float_to_tensor = torch.tensor([0.0, 1.0,2.0, 3.0, 4.0])
float_to_tensor

tensor([0., 1., 2., 3., 4.])

In [9]:
print('The dtype of tensor object after converting it to tensors==> ',float_to_tensor.dtype)
print('The type of tensor after converting it to a tensor==> ',float_to_tensor.type())

The dtype of tensor object after converting it to tensors==>  torch.float32
The type of tensor after converting it to a tensor==>  torch.FloatTensor


In [10]:
# Convert a float python list to a float tensor : 
list_of_floats = [0.0, 1.0, 2.0, 3.0, 4.0]
float_int_tensors = torch.tensor(list_of_floats, dtype=torch.int64)
float_int_tensors

tensor([0, 1, 2, 3, 4])

In [11]:
float_int_tensors.type()

'torch.LongTensor'

In [12]:
float_int_tensors.dtype

torch.int64

From the previous examples, you see that torch.tensor() converts the list to the tensor type, which is similar to the original list type. However, what if you want to convert the list to a certain tensor type? torch contains the methods required to do this conversion. The following code converts an integer list to float tensor:

In [13]:
# Convert an integer list with length 5 to a float tensors:
new_float_tensor = torch.FloatTensor([1, 2, 3, 4, 5])
print('The type of the new tensor==> ',new_float_tensor.type())
print('The dtype of the new tensor==> ',new_float_tensor.dtype)

The type of the new tensor==>  torch.FloatTensor
The dtype of the new tensor==>  torch.float32


In [14]:
new_float_tensor = torch.FloatTensor([0, 1, 2, 3, 4])

In [15]:
# Another method to convert the integer list to float tensor:
old_int_tensor = torch.tensor([1, 2, 3, 4])
new_float_tensor = old_int_tensor.type(torch.FloatTensor)
print('The type of the new float tensor', new_float_tensor.type())
new_float_tensor

The type of the new float tensor torch.FloatTensor


tensor([1., 2., 3., 4.])

The tensor_obj.size() helps you to find out the size of the tensor_obj. The tensor_obj.ndimension() shows the dimension of the tensor object.

In [16]:
print('The size of the new_float_tensor==> ', new_float_tensor.size())
print('The number of dimensions of the new_float_tensors==>',new_float_tensor.ndimension(),'-Dimensional Tensor(Vector)')


The size of the new_float_tensor==>  torch.Size([4])
The number of dimensions of the new_float_tensors==> 1 -Dimensional Tensor(Vector)


The tensor_obj.view(row, column) is used for reshaping a tensor object.

What if you have a tensor object with torch.Size([5]) as a new_float_tensor as shown in the previous example?
After you execute new_float_tensor.view(5, 1), the size of new_float_tensor will be torch.Size([5, 1]).
This means that the tensor object new_float_tensor has been reshaped from a one-dimensional tensor object with 5 elements to a two-dimensional tensor object with 5 rows and 1 column.

In [17]:
# Introduce the tensor_obj.view(rows, columns) method:
twoD_float_tensor = new_float_tensor.view(4,1)
print('Original size: ', new_float_tensor)
print('Size after view method ', twoD_float_tensor)

Original size:  tensor([1., 2., 3., 4.])
Size after view method  tensor([[1.],
        [2.],
        [3.],
        [4.]])


In [18]:
twoD_float_tensor

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [19]:
twoD_float_tensor.ndimension()

2

In [20]:
# Introduce the use of -1 in tensor_obj.view(rows, columns)method
twoD_float_tensor = new_float_tensor.view(-1, 1)
print('Original size: ', new_float_tensor)
print('Size after view method ', twoD_float_tensor)

Original size:  tensor([1., 2., 3., 4.])
Size after view method  tensor([[1.],
        [2.],
        [3.],
        [4.]])


In [21]:
x = torch.tensor([2, 4, 5, 66])
p = x.view(-1, 1)
p

tensor([[ 2],
        [ 4],
        [ 5],
        [66]])

In [22]:
p.type()

'torch.LongTensor'

**Convert Numpy array to Tensors:**

In [23]:
numpy_array = np.array([0.0, 1.0, 2.0, 3.0, 4.0])
new_tensor = torch.from_numpy(numpy_array)
new_tensor 

tensor([0., 1., 2., 3., 4.], dtype=torch.float64)

In [24]:
print('The type of new_tensor object ', new_tensor.type())
print('The dtype of new_tensor object ', new_tensor.dtype)


The type of new_tensor object  torch.DoubleTensor
The dtype of new_tensor object  torch.float64


**Convert Tensors to numpy arrays:**

In [25]:
back_to_numpy = new_tensor.numpy()
back_to_numpy 

array([0., 1., 2., 3., 4.])

In [26]:
print('The dtype of back_to _numpy :', back_to_numpy.dtype)

The dtype of back_to _numpy : float64


back_to_numpy and new_tensor still point to numpy_array. As a result if we change numpy_array both back_to_numpy and new_tensor will change. For example if we set all the elements in numpy_array to zeros, back_to_numpy and  new_tensor will follow suit.


In [27]:
# set all elements in numpy array to zero: 
numpy_array[:] = 0
print('The new_tensor points to numpy_array : ', new_tensor)
print('The back_to_numpy array points to the tensor : ' ,back_to_numpy)

The new_tensor points to numpy_array :  tensor([0., 0., 0., 0., 0.], dtype=torch.float64)
The back_to_numpy array points to the tensor :  [0. 0. 0. 0. 0.]


**Convert pandas_series to Tensors:**

Pandas Series can also be converted by using the numpy array that is stored in pandas_series.values. Note that pandas_series can be any pandas_series object.

In [28]:
pandas_series = pd.Series([0.1, 2, 0.3, 10.1])
new_tensor = torch.from_numpy(pandas_series.values)
new_tensor

tensor([ 0.1000,  2.0000,  0.3000, 10.1000], dtype=torch.float64)

In [29]:
print('The dtype of the new_tensor : ', new_tensor.dtype)
print('The type of the new_tensor : ', new_tensor.type())

The dtype of the new_tensor :  torch.float64
The type of the new_tensor :  torch.DoubleTensor


**Indexing & Slicing:**

In [30]:
index_tensor = torch.tensor([55, 1, 3, 54, 11])
print('The value of index 0 : ', index_tensor[0])
print('The value of index 1 : ', index_tensor[1])
print('The value of index 2 : ', index_tensor[2])
print('The value of index 3 : ', index_tensor[3])


The value of index 0 :  tensor(55)
The value of index 1 :  tensor(1)
The value of index 2 :  tensor(3)
The value of index 3 :  tensor(54)


In [ ]:
# Change the value of 0 index to 200 : 
print('The inital value on index 0 : ', index_tensor[0])
index_tensor[0] = 200
print('Modified Tensor is : ', index_tensor)

The inital value on index 0 :  tensor(55)
Modified Tensor is :  tensor([200,   1,   3,  54,  11])


**Tensors Functions:**

In [ ]:
# Mean & standard Devition : 
x = torch.tensor([1.0 , -1.0, 1, -1])
x 

tensor([ 1., -1.,  1., -1.])

In [ ]:
mean = x.mean()
print('The mean of x : ', mean)

The mean of x :  tensor(0.)


In [ ]:
std = x.std()
print('The standard deviation of x : ', std)

The standard deviation of x :  tensor(1.1547)


In [ ]:
max_min_tensor = torch.tensor([1, 2, 3, 4, 5])
max_min_tensor 

tensor([1, 2, 3, 4, 5])

In [ ]:
# find the max value : 
max_val = max_min_tensor.max()
print('The maximum number in the tensor is : ', max_val)


The maximum number in the tensor is :  tensor(5)


In [ ]:
# find the min value : 
min_val = max_min_tensor.min()
print('The minimum number in the tensor is : ', min_val)


The minimum number in the tensor is :  tensor(1)


**Create Tensor by torch.linespace():**

A useful function for plotting mathematical functions is torch.linspace(). torch.linspace() returns evenly spaced numbers over a specified interval. You specify the starting point of the sequence and the ending point of the sequence. The parameter steps indicates the number of samples to generate. Now, you'll work with steps = 5.

In [ ]:
# First try on using linespace to create tensor : 
len_5_tensor = torch.linspace(-2, 2, steps= 5)
print('First Try on linespace',len_5_tensor)

First Try on linespace tensor([-2., -1.,  0.,  1.,  2.])


In [ ]:
# Assign steps with 9 : 
len_9_tensor = torch.linspace(-2, 2, steps=9)
print('Second Try on linespace', len_9_tensor)

Second Try on linespace tensor([-2.0000, -1.5000, -1.0000, -0.5000,  0.0000,  0.5000,  1.0000,  1.5000,
         2.0000])


**Tensors operations:**

In [31]:
# Addition : 
a = torch.tensor([1, 3])
b = torch.tensor([2, 3])
c = a + b 
c 

tensor([3, 6])

In [32]:
a = torch.tensor([3, 6])
b = torch.tensor([1, 2])
c = a - b 
c 

tensor([2, 4])

In [33]:
a = torch.tensor([2, 3, 4])
b = 10 + a 
b 

tensor([12, 13, 14])

In [34]:
a = torch.tensor([10, 20, 30, 40])
b = 2 * a 
b 

tensor([20, 40, 60, 80])

In [35]:
a = torch.tensor([2, 4, 6, 8])
b = torch.tensor([1, 3, 5, 7])
c = a * b 
c 

tensor([ 2, 12, 30, 56])

In [36]:
# Dot product : 
a = torch.tensor([1, 2])
b = torch.tensor([1, 2])
c = torch.dot(a, b)
c 

tensor(5)